# Generated by Django 4.1.4 on 2022-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employedetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedetail',
            name='employee_positions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
