# Generated by Django 4.1.4 on 2022-12-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_employedetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedetail',
            name='employee_positions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
