# Generated by Django 4.1.4 on 2022-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_employedetail_employee_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedetail',
            name='birthday',
            field=models.DateField(),
        ),
    ]
