# Generated by Django 4.1.4 on 2022-12-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_employedetail_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employedetail',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.AddField(
            model_name='employedetail',
            name='bonus',
            field=models.IntegerField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='employedetail',
            name='salary',
            field=models.IntegerField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='employedetail',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
        migrations.AddField(
            model_name='employedetail',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.role'),
        ),
    ]
