# Generated by Django 4.1.4 on 2022-12-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_employedetail_employee_positions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employedetail',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='employedetail',
            name='joining',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
